# Server port
server:
  port: 8082

spring:
  # Application name
  application:
    name: payment-service-app

client:
  dbmServiceBaseUrl: ${DBM_SERVICE_BASE_URL:http://localhost:8080}
  userServiceBaseUrl: ${USER_SERVICE_BASE_URL:http://localhost:8081}
