# Server port
server:
  port: 80

spring:
  # Application name
  application:
    name: landing-app
  # Spring data source definition
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/parcelapp-db"
    username: "parcelapp-user"
    password: "parcelapp-pass"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  # Spring-Flyway configuration
  flyway:
    locations: db/migration/postgresql
  # The below property has been added to support other HTTP verbs than GET and POST in Thymeleaf's forms (using th:method="")
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# Flyway configuration
flyway:
  url: jdbc:postgresql://localhost:3306/parcelapp-db
  schemas: USERSERVICE
  user: "parcelapp-user"
  password: "parcelapp-pass"