# Server port
server:
  port: 8080

spring:
  # Spring data source definition
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: "password"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  # Spring-Flyway configuration
  flyway:
    locations: db/migration/h2

# Flyway configuration
flyway:
  url: "jdbc:h2:mem:testdb"
  schemas: USERSERVICE
  username: "sa"
  password: "password"
