# Server port
server:
  port: 8080

spring:
  # Application name
  application:
    name: user-service-app
  # Spring data source definition
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  # Spring-Flyway configuration
  flyway:
    locations: db/migration/postgresql

# Flyway configuration
flyway:
  url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
  schemas: USERSERVICE
  user: "${DB_USER}"
  password: "${DB_PASS}"
